import type { CcnaLessonContent } from "./ccna-lesson-schema.ts";

type Teaching = Pick<CcnaLessonContent, "plainAnswer" | "sections" | "realWorldScenario" | "practiceQuestions" | "quiz" | "glossary" | "takeaways">;

// Stable instruction for this one foundational lesson, reviewed with the lab as a unit.
export function layeredTeaching(refs: { layers: string; routing: string; acl: string; ping: string; setup: string }): Teaching {
  return {
    plainAnswer: "A layered model is a diagram or checklist that organizes troubleshooting steps by grouping related network jobs. Use OSI and TCP/IP to ask about links, local delivery, routing and services, then collect evidence. A missing ping reply does not identify a faulty layer; a successful reply does not prove a web application works.",
    sections: [
      {
        heading: "Introduction to Layered Network Models",
        explanation: "A layered model is a diagram or checklist that organizes troubleshooting steps by grouping related network jobs. A layer is one group, not a separate physical box. OSI has seven layers: physical moves signals; data link handles local frames; network handles IP delivery; transport handles communication between applications; session organizes exchanges; presentation concerns data representation; application provides network functions used by software. These categories help organize questions, but the model does not detect faults on its own. One device or program may perform jobs associated with several layers. Consider a parcel-delivery checklist as a memory aid, not a literal delivery process: real devices do not forward packets like parcels. Asking about a destination is an organizational metaphor for checking an address, not a description of a router's actions. Asking whether a reply arrived is an organizational metaphor for checking a return path, not a postal mechanism implemented by a device.",
        example: "On paper, name PC1 as the source and PC2 as the destination. First ask whether the links exist, then whether addresses and gateways match the plan, and finally whether the tested traffic is permitted. The checklist suggests observations; it does not tell you the answer before you collect them.",
        keyPoints: ["A model organizes troubleshooting questions; it does not detect faults by itself.", "Seven OSI categories describe jobs, not seven separate devices.", "Every parcel comparison here is a memory aid, not literal device behavior."],
        sourceUrls: [refs.layers]
      },
      {
        heading: "Map OSI Jobs to the TCP/IP Path",
        explanation: "This lesson uses four TCP/IP layers. Link groups OSI physical and data link jobs; internet corresponds to OSI network jobs; transport corresponds to OSI transport; application groups OSI session, presentation and application jobs. Some textbooks split link into two and use a five-layer teaching convention. ICMP belongs with IP at the internet layer, not with TCP or UDP at transport. In our Ethernet path, PC1 puts an ICMP request in an IPv4 packet and carries that packet in a local frame. Switch forwards the local frame toward Router. Router removes that frame, reads the destination IP, chooses LAN2 and creates a new Ethernet frame addressed to PC2's MAC address. The outgoing frame's source MAC belongs to Router's LAN2 interface. The packet's source remains PC1 at 192.168.1.10 and its destination remains PC2 at 192.168.2.10: there is no NAT, or network address translation, in this lab. Not every packet bit is unchanged: Router reduces the IPv4 time-to-live (TTL), a forwarding limit, and updates the IPv4 header checksum, its error-check value.",
        example: "Router's LAN2 interface has IP 192.168.2.1, which is PC2's gateway. That is not a replacement source IP for PC1's forwarded request. PC2 receives the request addressed to 192.168.2.10 and generates its own reply to 192.168.1.10 through gateway 192.168.2.1.",
        keyPoints: ["A frame provides local delivery; the IP packet identifies the endpoint destination.", "Router creates a new Ethernet frame on its outgoing link.", "Without NAT, endpoint IP addresses stay the same; IPv4 TTL and checksum change at Router."],
        sourceUrls: [refs.layers, refs.routing]
      },
      {
        heading: "What a Ping Result Can and Cannot Tell You",
        explanation: "Ping asks a named IP peer to return an ICMP echo reply. A reply supports that particular request-and-reply exchange at that time, including the links and routing it depended on. It does not test TCP connections, UDP services or a web application. A missing reply means the exchange did not finish before the timeout, not that one specific layer failed. Check the destination identity, addressing, both path directions and relevant policy. In real networks, missed ping replies may involve host firewalls, link problems or rate limits, as well as routing and endpoint state. ARP discovers the MAC address of the local next hop; initial discovery can delay a first test. Repeated success is consistent with that possibility, but does not prove ARP caused an earlier timeout. Persistent or intermittent loss needs investigation before introducing a controlled fault.",
        example: "PC1 must ping 192.168.2.10 to test PC2. Pinging PC1's own 192.168.1.10 exercises its local IP stack, not the peer path. Pinging gateway 192.168.1.1 tests a shorter exchange. If the gateway replies but PC2 does not, investigate the remaining forward and return path; do not declare the entire network healthy or broken.",
        keyPoints: ["Use the named peer address, not a self-ping, for the before-and-after comparison.", "Host firewalls, link problems and rate limits are possible real-network causes of lost replies.", "A permit rule predicts permitted traffic; it does not prove untested applications work."],
        sourceUrls: [refs.ping, refs.layers]
      },
      {
        heading: "Read Layered Evidence and ACL Bindings",
        explanation: "Begin with read-only observations: inspect cable endpoints and interface state, compare addresses and gateways, and review the tested path and policy. An ACL is an ordered permit/deny rule list. Its identifier can be a number, such as 199, or a name. An ip access-group command binds that list to an interface: inbound means arriving at Router through that port; outbound means leaving Router through that port. A rule's match counter counts matching packets since the counter was last initialized or cleared. It is not the ACL identifier, the number of rules, or a rule sequence number. Counter availability and display vary by image. Correlate a supported counter change with the exact test, attachment and baseline; missing or stale counters are not proof of a particular cause. In real networks, missed ping replies may involve host firewalls, link problems or rate limits even when an ACL exists. An up/up interface is evidence about that local interface, not proof of end-to-end connectivity.",
        example: "Read this as an illustrative output interpretation, not a command to type: '10 deny icmp host 192.168.1.10 host 192.168.2.10 echo (6 matches)' means rule sequence 10 recorded six matches. The list heading identifies ACL 199. An interface's 'ip access-group 199 in' attaches that list inbound. Your output may differ; do not invent counts or expect exactly six matches.",
        keyPoints: ["ACL 199 identifies the list; a rule sequence and its match count are separate values.", "Inbound and outbound describe direction relative to the selected router interface.", "Inspect the complete configuration for other references and stop on unfamiliar ownership."],
        sourceUrls: [refs.acl, refs.ping]
      },
      {
        heading: "Use a Controlled Fault and Restore the Baseline",
        explanation: "Perform these tests only in the isolated lab setup, not on networks with production traffic or shared use. The detailed Practice network steps below supply the exact console actions; these teaching examples are paper predictions, not instructions to configure a device now. Establish repeated PC1-to-PC2 replies and save the clean baseline before creating a filter. ACL 199 must be unused, and the selected ports must have no pre-existing policy. The lab's narrow deny blocks PC1's echo requests to PC2. The following permit ip any any allows other IPv4 traffic evaluated by this ACL; it does not create routes, open services or demonstrate their health. Never copy this permissive teaching policy to production. Before rollback, compare the actual LAN1 interface with both your baseline and current interface inventory, then inspect every reference to 199. Stop if another interface or feature uses it. Detach only our known LAN1 inbound binding before deleting the lab-owned list, and repeat the identical peer test. This is our safety procedure, not a claim that IOS always prevents deletion of an attached definition. Copying startup-config into running-config merges settings and is not a reliable rollback.",
        example: "A baseline note records Router's actual LAN1 name, address 192.168.1.1/24, up/up status, no ACL attachment, the date and peer replies. During the fault, the known change is 'ip access-group 199 in' under that same port and our new list definition. After cleanup, both changes must be absent and repeated peer replies should match the original observation. Stop and investigate if they do not.",
        keyPoints: ["Use a clean, disposable, fully disconnected project and record the baseline before any fault.", "Inspect all references, detach the known lab-owned binding, then delete only the lab-owned list.", "An unexpected binding is a stop condition, not permission to remove every ACL.", "Successful cleanup requires configuration comparison as well as the original peer test."],
        sourceUrls: [refs.acl, refs.ping, refs.setup]
      }
    ],
    realWorldScenario: {
      title: "Investigate an Office Ping Report Without Removing Its Controls",
      situation: "An office reports that a server no longer replies to ping. This is a paper incident discussion, not an instruction to run the lab fault on that office. The responsible operator first confirms permission to inspect the relevant systems and gathers evidence without changing security policy.",
      walkthrough: [
        "Record the reported source, destination, time and affected service. A web-service complaint and an ICMP timeout are different observations; ask which was actually measured.",
        "Within the approved read-only scope, compare cable and interface state, addresses, gateways and the recorded path with the known baseline. An up/up port alone does not prove the server is reachable.",
        "Consider both directions and endpoint behavior. Missed ping replies may involve host firewalls, link problems or rate limits, not only router ACLs.",
        "Ask the authorized operator to inspect the relevant ACL identifiers, interface directions and supported match counters. Treat deliberately filtered ICMP as possible intended policy, not automatically a fault to remove.",
        "Report what is known and what remains uncertain. An approved service-specific test may be needed; this lesson's isolated lab does not run a production web-service test.",
        "Do not detach or delete office ACLs as a diagnostic shortcut. Any real change requires the organization's approval and rollback process. Reproduce the educational before/fault/after exercise only in the fully disconnected disposable lab."
      ],
      takeaway: "A layered model guides evidence collection, not automatic removal of security controls. Separate observations from hypotheses, preserve intended policy and get the appropriate authorization. The concrete ACL creation and rollback sequence in this lesson belongs only to its isolated lab."
    },
    practiceQuestions: [
      { question: "PC1 cannot ping PC2, although Router's mapped ports show up/up and addresses match the plan. What read-only evidence could you inspect next?", answer: "Inspect the tested forward and return path, including the relevant ACL binding and supported rule counters.", explanation: "Up/up is local interface evidence, not proof of peer connectivity. The ACL is one hypothesis. Compare the exact source and destination, gateway settings and policy; real host firewalls, link problems or rate limits can also affect replies." },
      { question: "A first peer ping times out, then repeated tests reply. Name one possible explanation and what the observation does not prove.", answer: "Initial ARP discovery may have delayed a test. Repeated replies alone do not prove ARP caused the earlier timeout.", explanation: "ARP resolves the local next-hop MAC address. On PC1's cross-subnet request, that next hop is its gateway, not remote PC2. Transient loss can have other causes, so record the observation and establish a stable baseline before the controlled fault." },
      { question: "PC1 receives gateway replies but not PC2 replies. Does that prove Router's ACL is the cause?", answer: "No. A gateway test covers a shorter exchange and does not establish the full PC2 forward and return path.", explanation: "Check actual peer addresses, both gateways, the remaining links and policy evidence. General hosts may also block ICMP or be unavailable. Those are conceptual alternatives; this VPCS lab does not simulate a host firewall product." },
      { question: "During isolated-lab cleanup, you discover an unfamiliar second reference to ACL 199. Should you detach every reference and delete the list?", answer: "No. Stop without changing it, because the list is not proven to belong solely to this exercise.", explanation: "Perform rollback only in the isolated lab, never on production or shared networks. The required baseline had no 199. This lab authorizes only its known LAN1 inbound binding; another interface or feature reference breaks that ownership assumption. Detachment-before-deletion is a safety procedure, not a guarantee enforced by IOS." },
      { question: "The deny counter does not change after PC1's failed peer ping. Which checks prevent an unsupported conclusion?", answer: "Verify the actual source and destination, mapped LAN1 inbound binding, exact rule match and whether this image exposes current counters.", explanation: "Read the complete running configuration and relevant interface output in the Router console. A wrong port, direction, source or target can prevent a match; unavailable counters are also a measurement limitation. Do not invent a count or conclude that missing counts prove routing is broken." },
      { question: "After the isolated rollback, PC1 receives repeated replies from PC2. What is verified, and what still needs a separate test?", answer: "The tested IP/ICMP exchange replies again. Web-service availability or performance is not established.", explanation: "Compare the same peer test and the recorded configuration baseline before calling the lab restored. Successful ICMP does not establish TCP/UDP services or application health. Any application test belongs to a separately authorized environment; there is no web server in this lab." }
    ],
    quiz: [
      { question: "In this lesson's four-layer TCP/IP model, where does ICMP belong?", options: ["Application", "Internet", "Transport", "Link"], correctIndex: 1, explanation: "ICMP is carried with IP at the internet layer, corresponding to OSI's network layer (Layer 3). The TCP/IP link layer groups OSI physical and data link jobs; our Ethernet switch performs local Layer 2 forwarding. Ping is not a TCP or UDP transport test." },
      { question: "PC1's request is routed to PC2 without NAT. Which description is correct?", options: ["Router replaces PC1's source IP with 192.168.2.1", "Router forwards the incoming Ethernet frame unchanged", "Router builds a new frame; endpoint IP addresses stay the same", "Switch assigns a new destination IP address"], correctIndex: 2, explanation: "Router uses its LAN2 MAC address as the outgoing frame's source MAC and PC2's MAC as destination. The request's source IP remains PC1 and destination IP remains PC2. Router updates forwarding-related IPv4 fields such as TTL and the header checksum; the entire packet is not bit-for-bit unchanged." },
      { question: "After confirming sole lab ownership and detaching ACL 199's only binding, which global configuration command deletes the numbered list?", options: ["no access-list 199", "delete access-list 199", "clear access-group 199", "erase startup-config"], correctIndex: 0, explanation: "Use no access-list 199 only after verifying ownership and detaching the list from its interface. All references must be checked first. This lab permits removing only its known LAN1 inbound binding; if another interface or feature references 199, stop instead of changing it. Detachment is our safe cleanup order, not an assertion that IOS automatically blocks deletion." },
      { question: "A peer ping succeeds. Which conclusion is supported by that result alone?", options: ["Every application on the peer is healthy", "TCP and UDP ports are all reachable", "No firewall exists anywhere on the path", "The tested ICMP request-and-reply exchange completed"], correctIndex: 3, explanation: "Ping supports the observed IP/ICMP round trip at that time. It relies on underlying links but does not test every protocol, service or application. A firewall may allow ICMP while filtering other traffic. Web-service checks require a separate authorized test." },
      { question: "What does 'in' mean in Router's ip access-group 199 in command on mapped LAN1?", options: ["Packets arriving at Router through LAN1", "Packets leaving Router through LAN1", "Every packet on every router interface", "Only replies generated by PC2"], correctIndex: 0, explanation: "Inbound is relative to the selected interface: the ACL evaluates packets arriving at Router through LAN1. Outbound would evaluate packets leaving that interface. Confirm the full mapped interface name and current binding before any change; do not apply the example to an unrelated port." }
    ],
    glossary: [
      { term: "Layered model", meaning: "A diagram or checklist that organizes related network jobs for troubleshooting. It helps structure questions, but does not detect faults by itself." },
      { term: "Frame and packet", meaning: "An Ethernet frame delivers data on one local link. The IPv4 packet inside names IP endpoints; routing creates a new outgoing Ethernet frame." },
      { term: "Inbound and outbound", meaning: "Inbound traffic arrives at a router through the selected interface. Outbound traffic leaves through that interface. Direction is relative to that port." },
      { term: "ACL binding", meaning: "An ip access-group setting attaches an access control list to a named interface and direction. A list definition and its attachment are separate configuration items." },
      { term: "Match counter", meaning: "A per-rule count of matched packets since initialization or clearing, where the platform exposes it. It is not an ACL identifier or rule sequence number." },
      { term: "Peer test", meaning: "A test to the other named endpoint, such as PC1 testing PC2, rather than testing the source computer's own address." },
      { term: "Baseline and rollback", meaning: "The baseline records the clean configuration and repeatable observations. Rollback removes only authorized changes and verifies that recorded state again." },
      { term: "Permit ip any any", meaning: "After the narrow deny in this example, this rule permits other IPv4 traffic evaluated by the ACL. Do not copy this permissive teaching policy to production; it does not itself create routes or services." },
      { term: "TTL and NAT", meaning: "IPv4 time-to-live (TTL) limits forwarding hops. Network address translation (NAT) changes IP addresses under a configured translation policy; it is not present in this lab." }
    ],
    takeaways: ["Use layers to organize evidence, not to guess a faulty device from one timeout.", "Track both endpoint IP addresses separately from the changing local Ethernet frames.", "A peer ping tests one ICMP exchange; it does not establish application health.", "Use only an isolated disposable lab with the exact mapped interfaces and a clean baseline.", "Stop on unfamiliar ACL references; detach the known lab binding before deleting its list.", "Compare the same peer tests and configuration before and after rollback; never claim an unexecuted test passed."]
  };
}
