export const ccnaTeachingPolicyVersion = 3;

export const ccnaBeginnerWritingPolicy = [
  "AUDIENCE: An adult with no prior computer or networking knowledge. Write respectfully, not in a childish voice. Do not assume the reader knows a browser, file, program, port, address, terminal, or the meaning of a command.",
  "Use common English, mostly 10-18 word sentences and one idea per sentence. Explain technical words and expand unfamiliar abbreviations at first use, before building on them. Keep accurate technical names and syntax after their plain-English meaning. Avoid vague language such as evidence-led methodology, operationalize, simply, just, obviously, or as everyone knows.",
  "BeginnerGuide is required. Explain the starting knowledge in place, why the topic matters, one familiar everyday comparison, its exact networking meaning, and where that comparison stops being accurate. Include a fully worked 3-6 step example with what happens and why at each step, a safe tiny practice task with an expected observation and a specific hint, and an understanding question with a hint and reasoned answer.",
  "Prerequisites must be concrete tasks or named earlier lessons with a short recap, never vague basic networking knowledge. The free /courses/ccna/start-here guide covers computer parts, clicking and typing, files and apps, browsers, Internet versus Wi-Fi, addresses and safe lab setup. Day one assumes no IP-addressing knowledge; explain an address, a subnet mask, /24, a console and Enter before showing the first command.",
  "Move from a fully worked example to guided practice and then an independent quiz. Each exercise must use only ideas already taught in this lesson or explicitly recapped from earlier lessons. Offer an observation or paper alternative when the learner has only a phone or cannot yet install the lab; never imply that paper practice replaces hands-on verification.",
  "For each lab step, name the exact window, device and command context. State what to click or type, whether to press Enter, what appears next, and how to recover from a common mistake. commandExplanations must have exactly one entry for each command, in order. Explain its words, numbers, punctuation, placeholders, units and purpose. Never present the command prompt as part of the command to type. Do not remove necessary technical precision to make a sentence shorter.",
  "Put essential definitions next to their first use and also collect them in the glossary. Explain why incorrect quiz choices are wrong. Do not test acronym recall before teaching the concept. Reading metrics and word counts are screening signals, not proof that a real beginner understands. Avoid promises that everyone learns at the same pace or will pass an exam."
].join(" ");

export const ccnaBeginnerReviewPolicy = "Also review as a reader who has never used a computer. Reject hidden prerequisite knowledge, undefined essential jargon, missing click/type/Enter instructions, unexplained command arguments, analogies presented as literal facts, and exercises that introduce untaught ideas. Check that the beginner example actually teaches this topic, every hint helps recover a specific difficulty, and every command explanation matches its exact command. Preserve correct terminology and safety boundaries. Do not approve merely because sentences are short or the guide fields exist.";
